name: Pack artifacts

on:
  push:

jobs:
  build:
    uses: ./.github/workflows/build_ws_server.yaml

  artifacts:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/main'

    steps:  
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: x86-artifacts
          path: config/config.json
