name: Build for macOS

on:
  push:
    branches:
      - main

jobs:
  build:
    uses: ./.github/workflows/reusable.yaml

  artifacts:
    runs-on: ubuntu-latest
    if: ${{ github.ref in ('refs/heads/main', 'refs/heads/dev') }}

    steps:  
      # - name: Build arm64
      #   run: GOOS=linux GOARCH=arm64 go build -o app_arm64

      # - name: Test
      #   run:  |
      #         go test -coverprofile=coverage.out  ./... 
      #         go tool cover -html=coverage.out -o report.html
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: x86-artifacts
          path: config/config.json
        
      - name: Upload Coverage
        uses: actions/upload-artifact@v3
        with:
          name: report.html
          path: report.html
