name: Build for macOS

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19  # Replace with your desired Go version

      - name: Build x86
        run: go build -o app 

      - name: Create Artifacts
        run: |
          mkdir artifacts
          touch artifacts/app

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: x86-artifacts
          path: artifacts/app
        
      # - name: Upload Coverage
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: report.html
      #     path: report.html
